import type { HandpanConfig } from './types';
import { generateHandpanLayout } from './layoutHelpers';

export const HANDPAN_CONFIGS: HandpanConfig[] = [
  {
    id: 'd-kurd-9',
    name: 'D Kurd 9',
    family: 'Kurd',
    scaleName: 'Kurd',
    scaleAliases: ['D Kurd', 'Kurd Minor', 'Integral Minor'],
    scaleMoodTags: ['versatile', 'balanced', 'atmospheric', 'open'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'The most popular handpan scale. Versatile and balanced, perfect for beginners. Creates an open, atmospheric sound.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'd-kurd-10',
    name: 'D Kurd 10',
    family: 'Kurd',
    scaleName: 'Kurd',
    scaleAliases: ['D Kurd', 'Kurd Minor', 'Integral Minor'],
    scaleMoodTags: ['versatile', 'balanced', 'atmospheric', 'open'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'The most popular handpan scale. Versatile and balanced, perfect for beginners. Creates an open, atmospheric sound.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5', 'Bb5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5', 'Bb5'], 'D4'),
  },
  {
    id: 'd-kurd-13',
    name: 'D Kurd 13',
    family: 'Kurd',
    scaleName: 'Kurd',
    scaleAliases: ['D Kurd', 'Kurd Minor', 'Integral Minor'],
    scaleMoodTags: ['versatile', 'balanced', 'atmospheric', 'open'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'The most popular handpan scale. Versatile and balanced, perfect for beginners. Creates an open, atmospheric sound.',
    notes: [
      'D4',
      'A4',
      'Bb4',
      'C5',
      'D5',
      'E5',
      'F5',
      'G5',
      'A5',
      'Bb5',
      'C6',
      'D6',
      'E6',
    ],
    layout: generateHandpanLayout([
      'D4',
      'A4',
      'Bb4',
      'C5',
      'D5',
      'E5',
      'F5',
      'G5',
      'A5',
      'Bb5',
      'C6',
      'D6',
      'E6',
    ], 'D4'),
  },
  {
    id: 'celtic',
    name: 'Celtic',
    family: 'Celtic',
    scaleName: 'Celtic Minor',
    scaleAliases: ['Amara', 'Celtic'],
    scaleMoodTags: ['deep', 'enchanting', 'soul-soothing', 'mystical'],
    scaleTypicalKeys: ['D', 'E', 'B'],
    scaleDescription: 'A hexatonic scale with a deep, enchanting quality. Often compared to Kurd but with a more mystical character.',
    notes: ['D4', 'E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D5', 'E5'],
    layout: generateHandpanLayout(['D4', 'E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D5', 'E5'], 'D4'),
  },
  {
    id: 'pygmy',
    name: 'Pygmy',
    family: 'Pygmy',
    scaleName: 'Pygmy',
    scaleAliases: ['Pygmy Minor'],
    scaleMoodTags: ['tribal', 'rhythmic', 'energetic', 'primal'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'A rhythmic, energetic scale with a tribal feel. Great for percussive playing and rhythmic patterns.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'equinox',
    name: 'Equinox',
    family: 'Equinox',
    scaleName: 'Equinox',
    scaleAliases: ['F# Equinox'],
    scaleMoodTags: ['bright', 'joyous', 'uplifting', 'rare'],
    scaleTypicalKeys: ['F#'],
    scaleDescription: 'A rare minor scale known for its bright and joyous expression. Uniquely uplifting among minor scales.',
    notes: ['F#4', 'C#5', 'D5', 'E5', 'F#5', 'G#5', 'A5', 'B5', 'C#6'],
    layout: generateHandpanLayout(['F#4', 'C#5', 'D5', 'E5', 'F#5', 'G#5', 'A5', 'B5', 'C#6'], 'F#4'),
  },
  {
    id: 'hijaz',
    name: 'Hijaz',
    family: 'Hijaz',
    scaleName: 'Hijaz',
    scaleAliases: ['D Hijaz', 'Hijaz Minor'],
    scaleMoodTags: ['exotic', 'oriental', 'profound', 'classical'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'Derived from classical Arabic music. Recognized for its unique, exotic sound with a profound musical legacy.',
    notes: ['D4', 'A4', 'Bb4', 'C#5', 'D5', 'E5', 'F5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C#5', 'D5', 'E5', 'F5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'magic-voyage',
    name: 'Magic Voyage',
    family: 'Magic Voyage',
    scaleName: 'Magic Voyage',
    scaleAliases: ['Magic Travel', 'Voyage'],
    scaleMoodTags: ['melodic', 'flowing', 'dreamy', 'adventurous'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'A melodic scale that creates a flowing, dreamy atmosphere. Perfect for storytelling and meditative playing.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F#5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F#5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'annaziska',
    name: 'AnnaZiska',
    family: 'AnnaZiska',
    scaleName: 'AnnaZiska',
    scaleAliases: ['Integral', 'Integral Minor'],
    scaleMoodTags: ['balanced', 'harmonious', 'versatile', 'open'],
    scaleTypicalKeys: ['D', 'C#'],
    scaleDescription: 'A hexatonic variation that omits the 4th scale degree, creating a balanced and harmonious sound.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'mystic',
    name: 'Mystic',
    family: 'Mystic',
    scaleName: 'Mystic',
    scaleAliases: ['Mystic Minor'],
    scaleMoodTags: ['mysterious', 'contemplative', 'introspective', 'spiritual'],
    scaleTypicalKeys: ['D'],
    scaleDescription: 'A beginner-friendly D minor family scale with a mysterious, contemplative character. Great for introspective playing.',
    notes: ['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'],
    layout: generateHandpanLayout(['D4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'], 'D4'),
  },
  {
    id: 'ionian',
    name: 'Ionian',
    family: 'Ionian',
    scaleName: 'Ionian',
    scaleAliases: ['Major'],
    scaleMoodTags: ['bright', 'happy', 'uplifting', 'classic'],
    scaleTypicalKeys: ['C', 'D', 'G'],
    scaleDescription: 'The classic major scale. Bright, happy, and uplifting. Less common on handpans but offers a cheerful alternative.',
    notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'D5'],
    layout: generateHandpanLayout(['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'D5'], 'C4'),
  },
  {
    id: 'dorian',
    name: 'Dorian',
    family: 'Dorian',
    scaleName: 'Dorian',
    scaleAliases: ['Dorian Mode'],
    scaleMoodTags: ['jazzy', 'sophisticated', 'minor-like', 'versatile'],
    scaleTypicalKeys: ['D', 'A'],
    scaleDescription: 'A minor-like mode with a raised 6th. More sophisticated and jazzy than pure minor scales.',
    notes: ['D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'D5', 'E5'],
    layout: generateHandpanLayout(['D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'D5', 'E5'], 'D4'),
  },
  {
    id: 'lydian',
    name: 'Lydian',
    family: 'Lydian',
    scaleName: 'Lydian',
    scaleAliases: ['Lydian Mode'],
    scaleMoodTags: ['dreamy', 'ethereal', 'floating', 'mystical'],
    scaleTypicalKeys: ['F', 'C'],
    scaleDescription: 'A major mode with a raised 4th. Creates a dreamy, floating quality with an ethereal character.',
    notes: ['F4', 'G4', 'A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5'],
    layout: generateHandpanLayout(['F4', 'G4', 'A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5'], 'F4'),
  },
  {
    id: 'mixolydian',
    name: 'Mixolydian',
    family: 'Mixolydian',
    scaleName: 'Mixolydian',
    scaleAliases: ['Mixolydian Mode'],
    scaleMoodTags: ['bluesy', 'rock', 'folk', 'grounded'],
    scaleTypicalKeys: ['G', 'D'],
    scaleDescription: 'A major mode with a lowered 7th. Bluesy and grounded, popular in rock and folk music.',
    notes: ['G4', 'A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'],
    layout: generateHandpanLayout(['G4', 'A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'], 'G4'),
  },
  {
    id: 'aeolian',
    name: 'Aeolian',
    family: 'Aeolian',
    scaleName: 'Aeolian',
    scaleAliases: ['Natural Minor', 'Minor'],
    scaleMoodTags: ['melancholic', 'emotional', 'expressive', 'classic'],
    scaleTypicalKeys: ['A', 'D', 'E'],
    scaleDescription: 'The natural minor scale. Melancholic and emotional, offering deep expressive possibilities.',
    notes: ['A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5', 'B5'],
    layout: generateHandpanLayout(['A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5', 'B5'], 'A4'),
  },
];

export function getHandpanConfig(id: string): HandpanConfig | undefined {
  return HANDPAN_CONFIGS.find((config) => config.id === id);
}

export function getAllHandpanConfigs(): HandpanConfig[] {
  return HANDPAN_CONFIGS;
}
